sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - yarn test
  - yarn test:with-setup
after_success:
  - codecov
branches:
  only:
    - master